// Retrieval practice: one direction and one question at a time.
const wordLessonRenderer=renderVocabulary;
renderVocabulary=function(){wordLessonRenderer();for(const lang of ['en','de']){
 const root=$(lang+'Words');root.querySelectorAll('.word details').forEach(x=>x.remove());
 const name=lang==='en'?'英语':'德语';const controls=document.createElement('div');controls.className='quiz-controls';controls.innerHTML='<button type="button" data-direction="forward">'+name+'随机测试：看中文写单词</button><button type="button" class="secondary" data-direction="reverse">'+name+'随机测试：看单词写中文</button>';
 root.prepend(controls);controls.querySelectorAll('button').forEach(button=>button.onclick=()=>startWordQuiz(lang,button.dataset.direction));
}};
const quizDialog=document.createElement('dialog');quizDialog.className='word-quiz';document.body.append(quizDialog);
let activeQuiz=null;
function shuffleWords(words){const result=words.map(x=>[...x]);for(let i=result.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[result[i],result[j]]=[result[j],result[i]]}if(result.length>1&&result.every((x,i)=>x[0]===words[i][0]))result.push(result.shift());return result}
function quizRecord(lang,direction){const prompt=(lang==='en'?'英语':'德语')+' / 随机词测 '+direction;let record=languageExercises.find(x=>x.prompt===prompt);if(!record){record={prompt,response:'',answer:''};languageExercises.push(record)}return record}
function startWordQuiz(lang,direction){const record=quizRecord(lang,direction);let stored;try{stored=JSON.parse(record.response)}catch{}const words=dailyWords(lang).filter(x=>Array.isArray(x)&&x.length>=2&&x.every(v=>typeof v==='string'&&v.trim()));const valid=stored?.date===viewedDate&&Number.isInteger(stored.index)&&stored.index>=0&&Array.isArray(stored.words)&&stored.words.length===words.length&&stored.index<stored.words.length&&Array.isArray(stored.answers)&&stored.words.every(x=>Array.isArray(x)&&words.some(w=>w[0]===x[0]&&w[1]===x[1]));activeQuiz={lang,direction,record,state:valid?stored:{date:viewedDate,words:shuffleWords(words),index:0,answers:[]}};if(!quizDialog.open)quizDialog.showModal();paintQuiz();quizDialog.scrollTop=0}
function persistQuiz(){activeQuiz.record.response=JSON.stringify(activeQuiz.state);scheduleDraft()}
function paintQuiz(){const {state,direction}=activeQuiz,index=state.index;quizDialog.innerHTML='<button type="button" class="secondary quiz-close">退出并保存</button><p class="hint">随机词汇测试 · '+(direction==='forward'?'中文 → 外语':'外语 → 中文')+'</p>';
 quizDialog.querySelector('.quiz-close').onclick=()=>{persistQuiz();quizDialog.close()};
 if(index>=state.words.length){quizDialog.insertAdjacentHTML('beforeend','<h2>本轮已完成</h2><p>已提交 '+state.answers.length+' 题。中文同义表达将由复盘核对。</p>');return}
 const [word,meaning]=state.words[index],answer=state.answers[index];
 quizDialog.insertAdjacentHTML('beforeend','<p>'+ (activeQuiz.lang==='en'?'英语':'德语') +' · 第 '+(index+1)+' / '+state.words.length+' 题</p><div class="quiz-question-card"><p>'+(direction==='forward'?'中文题面，请写出对应单词':'单词题面，请写出中文意思')+'</p><div id="quizQuestion" role="heading" aria-level="2" translate="no">'+safeHtml(direction==='forward'?meaning:word)+'</div></div><label>你的答案<input id="quizAnswer" autocomplete="off" spellcheck="false"></label><button id="quizSubmit" type="button">提交答案</button><div id="quizFeedback" role="status"></div>');
 $('quizAnswer').value=answer?.response||state.pending||'';$('quizAnswer').oninput=()=>{state.pending=$('quizAnswer').value;persistQuiz()};
 $('quizSubmit').onclick=()=>{const response=$('quizAnswer').value.trim();if(!response){$('quizFeedback').textContent='请先填写答案。';return}const expected=direction==='forward'?word:meaning;state.answers[index]={word,question:direction==='forward'?meaning:word,response,expected,judgement:norm(response)===norm(expected)?'匹配':direction==='reverse'?'待核对同义表达':'需复习'};state.pending='';persistQuiz();revealQuizAnswer()};
 if(answer)revealQuizAnswer();quizDialog.scrollTop=0;
}
function revealQuizAnswer(){const item=activeQuiz.state.answers[activeQuiz.state.index];$('quizAnswer').disabled=true;$('quizSubmit').hidden=true;$('quizFeedback').textContent=item.judgement+'。参考答案：'+item.expected;const next=document.createElement('button');next.textContent='下一题';next.onclick=()=>{activeQuiz.state.index++;persistQuiz();paintQuiz()};$('quizFeedback').append(document.createElement('br'),next)}
quizDialog.addEventListener('cancel',()=>{if(activeQuiz)persistQuiz()});
const reviewSection=taskSection('昨日少量补练与写作反馈','targeted-review');taskNav.after(reviewSection);
function renderTargetedReview(){const root=reviewSection.querySelector('.task-content'),items=planOverride?.carryover||[];root.replaceChildren();if(!items.length){root.textContent='没有已确认的昨日补练。今天按新任务学习。';reviewSection.open=false;return}reviewSection.open=true;for(const item of items){const card=document.createElement('article');card.className='resource';const heading=document.createElement('h3');heading.textContent=item.title;const feedback=document.createElement('p');feedback.textContent=item.feedback||'等待具体批改；先不要求整篇重写。';const prompt='补练 / '+item.title;let record=languageExercises.find(x=>x.prompt===prompt);if(!record){record={prompt,response:'',answer:''};languageExercises.push(record)}const input=document.createElement('textarea');input.placeholder='根据上面的具体反馈修改这一项';input.value=record.response;input.oninput=()=>{record.response=input.value;scheduleDraft()};card.append(heading,feedback,input);root.append(card)}}
function applyRemedialMode(){
 const repeat=planOverride?.action==='repeat';
 for(const node of [englishStudy,germanStudy,outputSection,$('englishTasks')?.parentElement,$('languageExercises')?.parentElement,$('courseResources')])if(node)node.hidden=repeat;
 if(repeat){reviewSection.open=true;reviewSection.querySelector('summary').textContent='本日只补未完成 / 未通过项目（已通过的不重做）';if(!planOverride.carryover?.length)reviewSection.querySelector('.task-content').textContent='系统还没有逐项补做清单，不能安排整天重做。等待补齐验收依据。';$('planStatus').textContent='定向补做：只做清单中的项目，不是重做昨天全部作业。录音和随机词测可按清单需要使用。'}else reviewSection.querySelector('summary').textContent='今日追加补练（仅少量未完成 / 未通过项目）';
}
const reviewOutputRenderer=renderOutputs;renderOutputs=function(){reviewOutputRenderer();renderTargetedReview();applyRemedialMode()};
// A generic course is not an explanation of the specific question.
for(const day of [2,6]){for(const task of ENGLISH_TASKS[day])task.explanationUrl=''}
const writingRenderer=renderEnglish;renderEnglish=function(){writingRenderer();if([2,6].includes(lessonIndex())){const notice=document.createElement('p');notice.className='score-card';notice.textContent='已提交的初稿无需重复提交，也无需抄录官方原题。具体批改应以已安排的原题和提交记录为依据；读取失败属于系统问题，不算未完成。收到具体反馈后只修改指定部分。';$('englishTasks').prepend(notice)}};
const quizStyle=document.createElement('style');quizStyle.textContent='.quiz-controls{grid-column:1/-1;display:flex;gap:8px;flex-wrap:wrap}.word-quiz{box-sizing:border-box;width:min(92vw,520px);max-height:90dvh;overflow:auto;border:0;border-radius:18px;padding:24px;color:#172033}.word-quiz::backdrop{background:#10233fee}.word-quiz h2{font-size:28px;margin:24px 0}.quiz-close{float:right}.word-quiz input{margin:10px 0 18px}.word-quiz button{min-height:44px}#targeted-review{border-left:4px solid #e9a441}.word{min-width:0}';document.head.append(quizStyle);
const quizEntry=taskSection('单词随机测试 · 英语 / 德语','word-quiz-entry');
taskNav.after(quizEntry);
for(const lang of ['en','de'])for(const direction of ['forward','reverse']){const button=document.createElement('button');button.type='button';button.className='secondary';button.dataset.quizLang=lang;button.dataset.quizDirection=direction;button.textContent=(lang==='en'?'英语':'德语')+'：'+(direction==='forward'?'看中文写单词':'看单词写中文');button.onclick=()=>startWordQuiz(lang,direction);quizEntry.querySelector('.task-content').append(button)}
quizStyle.textContent+=' .quiz-question-card{background:#eef6ff;border:2px solid #155eef;border-radius:12px;padding:14px;margin:12px 0;color:#10233f}#quizQuestion{display:block!important;visibility:visible!important;font-size:28px;font-weight:800;line-height:1.4;overflow-wrap:anywhere}.quiz-question-card p{margin:0 0 8px;font-size:14px}#word-quiz-entry .task-content{display:flex;flex-wrap:wrap;gap:8px}.word-quiz{width:min(94vw,520px);max-height:85dvh}';
const originalPlanLoader=loadPlanOverride;
loadPlanOverride=async function(){await originalPlanLoader();try{const res=await fetch('plan-corrections.json?v=20260910-2',{cache:'no-store'});if(!res.ok)return;const correction=(await res.json())[viewedDate];if(correction&&(!planOverride||!planOverride.updatedAt||Date.parse(correction.updatedAt)>Date.parse(planOverride.updatedAt))){planOverride=correction;$('planStatus').textContent='今日计划已纠正：'+correction.reason}}catch{}};
// Resolve the final loader only after all enhancement scripts are initialized.
document.addEventListener('DOMContentLoaded',()=>{loadPlanOverride().finally(()=>loadDay())},{once:true});
